version: "3.8"

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./client:/app
  backend:
    build:
      context: ./project
    ports:
      - "8080:8080"
  
